### ISSUE TITLE
Crash ????

### ISSUE THREAD

**Issue by georgkrause** [apognu/otter#59] opened 2020-07-09 07:31 UTC
```
--------- beginning of crash
07-09 09:30:09.135 18454 18497 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-6
07-09 09:30:09.135 18454 18497 E AndroidRuntime: Process: com.github.apognu.otter, PID: 18454
07-09 09:30:09.135 18454 18497 E AndroidRuntime: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7760)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1225)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:23114)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:23114)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:23114)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:23114)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:23114)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:23114)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:23114)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:23114)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:23114)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:23114)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:23114)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at android.view.ViewGroup.bringChildToFront(ViewGroup.java:1612)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at android.view.View.bringToFront(View.java:14254)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setTargetOffsetTopAndBottom(SwipeRefreshLayout.java:1395)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.setRefreshing(SwipeRefreshLayout.java:494)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at com.github.apognu.otter.fragments.FunkwhaleFragment.fetch(FunkwhaleFragment.kt:104)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at com.github.apognu.otter.fragments.FunkwhaleFragment.fetch$default(FunkwhaleFragment.kt:100)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at com.github.apognu.otter.fragments.FunkwhaleFragment$fetch$$inlined$untilNetwork$1$1.emit(Collect.kt:136)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(Unknown Source:4)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:73)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:55)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at com.github.apognu.otter.repositories.Repository$fetch$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:133)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(Unknown Source:4)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:73)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:55)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at com.github.apognu.otter.repositories.Repository$fromCache$1.invokeSuspend(Repository.kt:48)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at com.github.apognu.otter.repositories.Repository$fromCache$1.invoke(Unknown Source:10)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:55)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:210)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:161)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect$suspendImpl(ChannelFlow.kt:138)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect(Unknown Source:0)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at com.github.apognu.otter.repositories.Repository$fetch$1.invokeSuspend(Repository.kt:62)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at com.github.apognu.otter.repositories.Repository$fetch$1.invoke(Unknown Source:10)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:55)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:210)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at com.github.apognu.otter.fragments.FunkwhaleFragment$fetch$$inlined$untilNetwork$1.invokeSuspend(Extensions.kt:81)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
07-09 09:30:09.135 18454 18497 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
07-09 09:30:09.188 18454 18497 I Process : Sending signal. PID: 18454 SIG: 9
```

**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Environment details**

 - Device:
 - Android version:
 - App version:
 - If public Funkwhale instance, its URL:

**Logs**

Add any related logs from ADB or from the "Copy logs" setting.

**Comment by apognu** [comment] 2020-07-09 21:35
This should be fixed, I'll close until you can tell me the issue is still present.

**Closed by apognu** 2020-07-09 21:35 UTC

**Comment by georgkrause** [comment] 2020-07-10 08:20
Well, this happened just randomly, so I can't try to reproduce anyway. Thanks for fixing! :)
