### ISSUE TITLE
App is unresponsive with lots of favorites

### ISSUE THREAD

**Issue by EliotBerriot** [apognu/otter#2] opened 2019-10-24 07:47 UTC
Hi, I've tried Otter on multiple pods, and it's working great, except on accounts that have lots of favorites.

Whenever I sign in with an account that has lots of favorites (~1000 during my test, but it may require less to trigger the issue), the app becomes completely unresponsive for me: I can't scroll, change tabs, open settings, etc.

In the background, otter is fetching for favorites (I can see the corresponding requests in the server logs). Even when the fetch is complete (no more HTTP requests sent), the app stays unresponsive.

I think it's related to the fact that Otter maintain a full cache of all the favorited tracks, which can be resource-hunghy with lots of tracks. It may be something else though.

A possible solution:

1. When app is loaded, send a single request to `/api/v1/favorites/tracks/all/` to retrieve the favorited track IDs and use this to power the favorite icon next to each track. This should be way faster and less resource-hungry, because you only need a single HTTP call, and only retrive a list of ids.
2. When the Favorites tab is visited, fetch the first page of favorites (and have the same behaviour as on albums / artists / playlists tabs, with infinite scrolling

I'm not really sure about the Shuffle button on the favorite tab, maybe shuffle/insert the first page, then fetch/insert other pages in the background and reshuffle when it's done?

If you cannot implement everything, I expect step 1 to fix the issue by making the app usable (even if the favorites tab isn't).

Let me know if there is anything I can do to help :)

**Comment by apognu** [comment] 2019-10-29 21:47
I was able to pinpoint the issue.

This is not related to network requests or memory consumption, but is actually caused by the embedding of a `RecyclerView` inside a `NestedScrollView` where Android struggles to compute the various sizes in the list.

I have not found a clean solution yet, so I will change the layout to bypass this issue for now. This should be available in the next update (tomorrow, I hope).

**Comment by EliotBerriot** [comment] 2019-10-30 10:24
Great news @apognu, I'll update and let you know if the issue is fixed when the release is pushed. Thank you!

**Comment by apognu** [comment] 2019-10-30 10:25
And I found a solution to keep the same layout (more or less) without the performance penalty. So it should be OK. I'll let you know when it's pushed.

**Comment by apognu** [comment] 2019-11-17 00:16
This should be fixed. Please reopen otherwise.

**Closed by apognu** 2019-11-17 00:16 UTC
Labels: bug

**Comment by EliotBerriot** [comment] 2019-11-17 10:06
I confirm this is fixed for me !
