### ISSUE TITLE
End of queue behavior

### ISSUE THREAD

**Issue by delcake** [apognu/otter#27] opened 2020-02-16 01:43 UTC
Once Otter has made it's way through all tracks in a queue, the Next Song button does not do anything. I'd suggest that pressing this button on the last song in the queue or after it has completed should restart the queue from the top.

**Comment by apognu** [comment] 2020-05-29 00:34
Hi,

This seems to be a duplicate of #26. I'll be closing this issue in favor of the other. Do not hesitate to reopen if you feel this is a different matter.

**Closed by apognu** 2020-05-29 00:34 UTC
